<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pv="https://ssl.selectpayment.com/PV">
	<soapenv:Header/>
	<soapenv:Body>
		<pv:AuthorizeTransaction>
			<pv:storeId><?=$this->e($credentials['store-id'])?></pv:storeId>
			<pv:storeKey><?=$this->e($credentials['store-key'])?></pv:storeKey>
			<pv:transaction>
				<pv:EntityId><?=$this->e($credentials['entity-id'])?></pv:EntityId>
				<pv:LocationId><?=$this->e($credentials['location-id'])?></pv:LocationId>
				<pv:PaymentOrigin><?=$this->e($trans->PaymentOrigin)?></pv:PaymentOrigin>
				<pv:AccountType><?=$this->e($trans->AccountType)?></pv:AccountType>
				<pv:OperationType>Auth</pv:OperationType>
				<pv:SettlementType><?=$this->e($trans->SettlementType)?></pv:SettlementType>
				<pv:EffectiveDate><?=$this->e($trans->EffectiveDate)?></pv:EffectiveDate>
				<pv:Description><?=$this->e($trans->Description)?></pv:Description>
				<pv:TotalAmount><?=$this->e($trans->TotalAmount)?></pv:TotalAmount>
				<pv:Sale></pv:Sale>
				<pv:ConvenienceFeeAmount></pv:ConvenienceFeeAmount>
				<pv:TerminalNumber><?=$this->e($trans->TerminalNumber)?></pv:TerminalNumber>
				<pv:TransactionNumber><?=$this->e($trans->TransactionNumber)?></pv:TransactionNumber>
				<pv:Field1></pv:Field1>
				<pv:Field2></pv:Field2>
				<pv:Field3></pv:Field3>
				<pv:CheckMICRLine></pv:CheckMICRLine>
				<pv:CheckMICRSymbolSet></pv:CheckMICRSymbolSet>
				<pv:RoutingNumber><?=$this->e($trans->RoutingNumber)?></pv:RoutingNumber>
				<pv:AccountNumber><?=$this->e($trans->AccountNumber)?></pv:AccountNumber>
				<pv:CheckNumber></pv:CheckNumber>
				<pv:SwipeTrack1></pv:SwipeTrack1>
				<pv:SwipeTrack2></pv:SwipeTrack2>
				<pv:SwipeTrack3></pv:SwipeTrack3>
				<pv:IsBusinessPayment>0</pv:IsBusinessPayment>
				<pv:NameOnAccount><?=$this->e($trans->NameOnAccount)?></pv:NameOnAccount>
				<pv:BillingAddress1><?=$this->e($trans->BillingAddress1)?></pv:BillingAddress1>
				<pv:BillingAddress2><?=$this->e($trans->BillingAddress2)?></pv:BillingAddress2>
				<pv:BillingCity><?=$this->e($trans->BillingCity)?></pv:BillingCity>
				<pv:BillingStateRegion><?=$this->e($trans->BillingStateRegion)?></pv:BillingStateRegion>
				<pv:BillingPostalCode><?=$this->e($trans->BillingPostalCode)?></pv:BillingPostalCode>
				<pv:BillingCountry><?=$this->e($trans->BillingCountry)?></pv:BillingCountry>
				<pv:BillingPhone><?=$this->e($trans->BillingPhone)?></pv:BillingPhone>
				<pv:IpAddressOfOriginator><?=$this->e($trans->IpAddressOfOriginator)?></pv:IpAddressOfOriginator>
				<pv:EmailAddress><?=$this->e($trans->EmailAddress)?></pv:EmailAddress>
				<pv:SSN></pv:SSN>
				<pv:DLState></pv:DLState>
				<pv:DLNumber></pv:DLNumber>
				<pv:CheckFrontImageBytes_TiffG4></pv:CheckFrontImageBytes_TiffG4>
				<pv:CheckRearImageBytes_TiffG4></pv:CheckRearImageBytes_TiffG4>
				<pv:OptionalThirdImageBytes_TiffG4></pv:OptionalThirdImageBytes_TiffG4>
				<pv:OptionalThirdImageDescription></pv:OptionalThirdImageDescription>
			</pv:transaction>
		</pv:AuthorizeTransaction>
	</soapenv:Body>
</soapenv:Envelope>
